import { Module } from "./lib/moduleKit";

const today = () => new Date().toISOString().slice(0, 10);

const profileFk = { table: "profiles", value: "id", label: "full_name" };
const customerFk = { table: "customers", value: "id", label: "name" };
const jobFk = { table: "jobs", value: "id", label: "job_no" };
const constructionFk = { table: "constructions", value: "id", label: "spec_no" };

const unitOptions = ["m", "kg", "pcs"];

export const modules = [
  new Module({
    key: "customers",
    label: "Customers",
    table: "customers",
    permissionModule: "customers",
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "contact", label: "Contact", type: "text" },
      { key: "email", label: "Email", type: "text" },
      { key: "gstin", label: "GSTIN", type: "text", mono: true },
      { key: "send_updates", label: "Send order updates by email", type: "checkbox", default: false },
      { key: "active", label: "Active", type: "checkbox", default: true },
    ],
  }),

  new Module({
    key: "constructions",
    label: "Constructions",
    table: "constructions",
    permissionModule: "constructions",
    orderBy: "spec_no",
    ascending: true,
    fields: [
      { key: "spec_no", label: "Spec No", type: "text", required: true, mono: true },
      { key: "family", label: "Family", type: "select", required: true, options: ["Narrow woven", "Fabric", "Cordage"] },
      { key: "product", label: "Product", type: "text", required: true },
      { key: "spec", label: "Specification", type: "text" },
      { key: "customer_id", label: "Customer", type: "select", fk: customerFk },
      { key: "status", label: "Status", type: "select", default: "Draft", options: ["Draft", "Released", "Obsolete"] },
      { key: "revision", label: "Revision", type: "text", default: "R0" },

      { key: "width_mm", label: "Width (mm)", type: "number", section: "Narrow woven", align: "right", mono: true },
      { key: "weave", label: "Weave", type: "text", section: "Narrow woven" },
      { key: "warp_denier", label: "Warp denier", type: "number", section: "Narrow woven", align: "right", mono: true },
      { key: "weft_denier", label: "Weft denier", type: "number", section: "Narrow woven", align: "right", mono: true },
      { key: "warp_ends", label: "Warp ends", type: "number", section: "Narrow woven", align: "right", mono: true },
      { key: "picks_per_cm", label: "Picks/cm", type: "number", section: "Narrow woven", align: "right", mono: true },
      { key: "selvedge", label: "Selvedge", type: "text", section: "Narrow woven" },

      { key: "width_cm", label: "Width (cm)", type: "number", section: "Broad fabric", align: "right", mono: true },
      { key: "epi", label: "EPI", type: "number", section: "Broad fabric", align: "right", mono: true },
      { key: "ppi", label: "PPI", type: "number", section: "Broad fabric", align: "right", mono: true },
      { key: "finish", label: "Finish", type: "text", section: "Broad fabric" },

      { key: "cord_type", label: "Cord type", type: "text", section: "Cordage" },
      { key: "diameter_mm", label: "Diameter (mm)", type: "number", section: "Cordage", align: "right", mono: true },
      { key: "carriers", label: "Carriers", type: "number", section: "Cordage", align: "right", mono: true },
      { key: "yarns_per_carrier", label: "Yarns/carrier", type: "number", section: "Cordage", align: "right", mono: true },
      { key: "core_yarns", label: "Core yarns", type: "number", section: "Cordage", align: "right", mono: true },
      { key: "yarn_denier", label: "Yarn denier", type: "number", section: "Cordage", align: "right", mono: true },
      { key: "tpm", label: "TPM", type: "number", section: "Cordage", align: "right", mono: true },
      { key: "contraction", label: "Contraction %", type: "number", section: "Cordage", align: "right", mono: true },

      { key: "warp_crimp", label: "Warp crimp %", type: "number", section: "Shared", align: "right", mono: true },
      { key: "weft_crimp", label: "Weft crimp %", type: "number", section: "Shared", align: "right", mono: true },
      { key: "warp_tenacity", label: "Warp tenacity (g/den)", type: "number", section: "Shared", align: "right", mono: true },
      { key: "weft_tenacity", label: "Weft tenacity (g/den)", type: "number", section: "Shared", align: "right", mono: true },
      { key: "efficiency", label: "Translation efficiency %", type: "number", default: 85, section: "Shared", align: "right", mono: true },
      { key: "notes", label: "Notes", type: "textarea", section: "Shared" },

      { key: "created_by", label: "Created by", type: "select", fk: profileFk, auto: true, hideInList: true },
      { key: "created_at", label: "Created", type: "date", computed: true, hideInForm: true, hideInList: true },
    ],
  }),

  new Module({
    key: "jobs",
    label: "Jobs",
    table: "jobs",
    permissionModule: "jobs",
    orderBy: "raised_on",
    fields: [
      { key: "job_no", label: "Job No", type: "text", required: true, mono: true },
      { key: "raised_on", label: "Raised on", type: "date", default: today },
      { key: "customer_id", label: "Customer", type: "select", fk: customerFk },
      { key: "po_ref", label: "PO ref", type: "text" },
      { key: "product", label: "Product", type: "text", required: true },
      { key: "spec", label: "Specification", type: "text" },
      { key: "construction_id", label: "Construction", type: "select", fk: constructionFk },
      { key: "width_mm", label: "Width (mm)", type: "number", align: "right", mono: true },
      { key: "colour", label: "Colour", type: "text" },
      { key: "qty_ordered", label: "Qty ordered", type: "number", required: true, align: "right", mono: true },
      { key: "unit", label: "Unit", type: "select", default: "m", options: unitOptions },
      { key: "qty_produced", label: "Qty produced", type: "number", default: 0, align: "right", mono: true },
      { key: "machine", label: "Machine", type: "text" },
      { key: "delivery_due", label: "Delivery due", type: "date" },
      { key: "status", label: "Status", type: "select", default: "Planned", options: ["Planned", "In Production", "Completed", "On Hold", "Cancelled"] },
      { key: "remarks", label: "Remarks", type: "textarea" },
      { key: "created_by", label: "Created by", type: "select", fk: profileFk, auto: true, hideInList: true },
    ],
  }),

  new Module({
    key: "downtime",
    label: "Downtime",
    table: "downtime",
    permissionModule: "downtime",
    orderBy: "logged_on",
    fields: [
      { key: "log_no", label: "Log No", type: "text", required: true, mono: true },
      { key: "logged_on", label: "Date", type: "date", default: today },
      { key: "shift", label: "Shift", type: "text", required: true },
      { key: "machine", label: "Machine", type: "text", required: true },
      { key: "reason", label: "Reason", type: "text", required: true },
      { key: "minutes", label: "Minutes", type: "number", required: true, align: "right", mono: true },
      { key: "job_id", label: "Job", type: "select", fk: jobFk },
      { key: "remarks", label: "Remarks", type: "textarea" },
      { key: "operator_id", label: "Operator", type: "select", fk: profileFk, auto: true, hideInList: true },
    ],
  }),

  new Module({
    key: "despatch",
    label: "Despatch",
    table: "despatch",
    permissionModule: "despatch",
    orderBy: "despatched_on",
    fields: [
      { key: "despatch_no", label: "Despatch No", type: "text", required: true, mono: true },
      { key: "despatched_on", label: "Date", type: "date", default: today },
      { key: "job_id", label: "Job", type: "select", required: true, fk: jobFk },
      { key: "invoice_no", label: "Invoice No", type: "text", mono: true },
      { key: "eway_bill", label: "E-way bill", type: "text", mono: true },
      { key: "qty", label: "Qty", type: "number", align: "right", mono: true },
      { key: "unit", label: "Unit", type: "select", default: "m", options: unitOptions },
      { key: "rolls", label: "Rolls", type: "number", align: "right", mono: true },
      { key: "gross_wt", label: "Gross weight", type: "number", align: "right", mono: true },
      { key: "transporter", label: "Transporter", type: "text" },
      { key: "lr_no", label: "LR No", type: "text", mono: true },
      { key: "destination", label: "Destination", type: "text" },
      { key: "status", label: "Status", type: "select", default: "Packed", options: ["Packed", "Despatched", "Delivered"] },
      {
        key: "override_reason",
        label: "Override reason (required only if the job has an open QC/lab failure)",
        type: "textarea",
      },
      { key: "created_by", label: "Created by", type: "select", fk: profileFk, auto: true, hideInList: true },
    ],
  }),

  new Module({
    key: "qc",
    label: "QC Checks",
    table: "qc_checks",
    permissionModule: "qc",
    orderBy: "checked_on",
    fields: [
      { key: "check_no", label: "Check No", type: "text", required: true, mono: true },
      { key: "job_id", label: "Job", type: "select", required: true, fk: jobFk },
      { key: "checked_on", label: "Date", type: "date", default: today },
      { key: "stage", label: "Stage", type: "text", required: true },
      { key: "family", label: "Family", type: "text" },
      { key: "parameter", label: "Parameter", type: "text", required: true },
      { key: "unit", label: "Unit", type: "text" },
      { key: "method", label: "Method", type: "text" },
      { key: "limit_type", label: "Limit kind", type: "select", required: true, default: "nominal", options: ["nominal", "minimum", "maximum", "range"] },
      { key: "spec_value", label: "Spec value", type: "number", required: true, align: "right", mono: true },
      { key: "tolerance", label: "Tolerance (±, nominal only)", type: "number", align: "right", mono: true },
      { key: "upper_limit", label: "Upper limit (range only)", type: "number", align: "right", mono: true },
      { key: "actual", label: "Actual reading", type: "number", align: "right", mono: true },
      { key: "defect_code", label: "Defect code", type: "text" },
      { key: "action_taken", label: "Action taken", type: "textarea" },
      { key: "inspector_id", label: "Inspector", type: "select", fk: profileFk, auto: true, hideInList: true },
      { key: "verdict", label: "Verdict", type: "text", computed: true, hideInForm: true, verdict: true },
    ],
  }),

  new Module({
    key: "tests",
    label: "Lab Tests",
    table: "lab_tests",
    permissionModule: "tests",
    orderBy: "tested_on",
    fields: [
      { key: "test_id", label: "Test ID", type: "text", required: true, mono: true },
      { key: "job_id", label: "Job", type: "select", fk: jobFk },
      { key: "tested_on", label: "Date", type: "date", default: today },
      { key: "test_type", label: "Test type", type: "text", required: true },
      { key: "standard", label: "Standard", type: "text" },
      { key: "lab", label: "Lab", type: "select", options: ["In-house", "SASMIRA", "SITRA", "NITRA"] },
      { key: "report_no", label: "Report No", type: "text", mono: true },
      { key: "requirement", label: "Requirement", type: "text" },
      { key: "result", label: "Result", type: "text" },
      { key: "unit", label: "Unit", type: "text" },
      { key: "verdict", label: "Verdict", type: "select", default: "Pending", options: ["PASS", "FAIL", "Pending"], verdict: true },
      { key: "retest_ref", label: "Retest ref", type: "text", mono: true },
      { key: "report_filed", label: "Report filed", type: "checkbox", default: false },
      { key: "remarks", label: "Remarks", type: "textarea" },
    ],
  }),

  new Module({
    key: "capa",
    label: "CAPA",
    table: "capa",
    permissionModule: "capa",
    orderBy: "raised_on",
    fields: [
      { key: "capa_no", label: "CAPA No", type: "text", required: true, mono: true },
      { key: "raised_on", label: "Raised on", type: "date", default: today },
      { key: "source", label: "Source", type: "text", required: true },
      { key: "reference", label: "Reference", type: "text" },
      { key: "job_id", label: "Job", type: "select", fk: jobFk },
      { key: "problem", label: "Problem", type: "textarea", required: true },
      { key: "root_cause", label: "Root cause", type: "textarea" },
      { key: "correction", label: "Correction", type: "textarea" },
      { key: "preventive", label: "Preventive action", type: "textarea" },
      { key: "owner_id", label: "Owner", type: "select", fk: profileFk },
      { key: "due_date", label: "Due date", type: "date" },
      { key: "status", label: "Status", type: "select", default: "Open", options: ["Open", "In Progress", "Closed"] },
      { key: "verified_by", label: "Verified by", type: "select", fk: profileFk },
    ],
  }),

  new Module({
    key: "recipes",
    label: "Dye Recipes",
    table: "dye_recipes",
    permissionModule: "recipes",
    orderBy: "dyed_on",
    fields: [
      { key: "recipe_no", label: "Recipe No", type: "text", required: true, mono: true },
      { key: "dyed_on", label: "Date", type: "date", default: today },
      { key: "job_id", label: "Job", type: "select", fk: jobFk },
      { key: "substrate", label: "Substrate", type: "text" },
      { key: "target_shade", label: "Target shade", type: "text" },
      { key: "batch_kg", label: "Batch (kg)", type: "number", align: "right", mono: true },
      { key: "dye1", label: "Dye 1", type: "text" },
      { key: "pct1", label: "% 1", type: "number", align: "right", mono: true },
      { key: "dye2", label: "Dye 2", type: "text" },
      { key: "pct2", label: "% 2", type: "number", align: "right", mono: true },
      { key: "dye3", label: "Dye 3", type: "text" },
      { key: "pct3", label: "% 3", type: "number", align: "right", mono: true },
      { key: "dye4", label: "Dye 4", type: "text" },
      { key: "pct4", label: "% 4", type: "number", align: "right", mono: true },
      { key: "liquor_ratio", label: "Liquor ratio", type: "text" },
      { key: "temp_c", label: "Temp (°C)", type: "number", align: "right", mono: true },
      { key: "time_min", label: "Time (min)", type: "number", align: "right", mono: true },
      { key: "ph", label: "pH", type: "number", align: "right", mono: true },
      { key: "auxiliaries", label: "Auxiliaries", type: "textarea" },
      { key: "shade_result", label: "Shade result", type: "text" },
      { key: "approved_by", label: "Approved by", type: "select", fk: profileFk },
    ],
  }),

  new Module({
    key: "skus",
    label: "Catalogue",
    table: "skus",
    permissionModule: "skus",
    orderBy: "sku_code",
    ascending: true,
    fields: [
      { key: "sku_code", label: "SKU Code", type: "text", required: true, mono: true },
      { key: "family", label: "Family", type: "select", required: true, options: ["Narrow woven", "Fabric", "Cordage"] },
      { key: "product", label: "Product", type: "text" },
      { key: "title", label: "Title", type: "text" },
      { key: "standard", label: "Standard", type: "text" },
      { key: "material", label: "Material", type: "text" },
      { key: "colour", label: "Colour", type: "text" },
      { key: "construction_id", label: "Construction", type: "select", fk: constructionFk },
      { key: "blurb", label: "Blurb", type: "textarea" },
      { key: "extra_props", label: "Extra properties", type: "textarea" },
      { key: "status", label: "Status", type: "select", default: "Draft", options: ["Draft", "Published", "Retired"] },
      { key: "created_by", label: "Created by", type: "select", fk: profileFk, auto: true, hideInList: true },
    ],
  }),

  new Module({
    key: "costing",
    label: "Costing",
    table: "costing",
    permissionModule: "costing",
    idField: "job_id",
    orderBy: "updated_at",
    fields: [
      { key: "job_id", label: "Job", type: "select", required: true, fk: jobFk, readOnlyOnEdit: true },
      { key: "qty", label: "Qty", type: "number", align: "right", mono: true },
      { key: "unit", label: "Unit", type: "select", default: "m", options: unitOptions },
      { key: "yarn_rate", label: "Yarn rate", type: "number", align: "right", mono: true },
      { key: "yarn_consumption", label: "Yarn consumption", type: "number", align: "right", mono: true },
      { key: "wastage_pct", label: "Wastage %", type: "number", align: "right", mono: true },
      { key: "dyeing", label: "Dyeing", type: "number", align: "right", mono: true },
      { key: "coating", label: "Coating", type: "number", align: "right", mono: true },
      { key: "labour", label: "Labour", type: "number", align: "right", mono: true },
      { key: "overhead", label: "Overhead", type: "number", align: "right", mono: true },
      { key: "packing", label: "Packing", type: "number", align: "right", mono: true },
      { key: "freight", label: "Freight", type: "number", align: "right", mono: true },
      { key: "margin_pct", label: "Margin %", type: "number", align: "right", mono: true },
      { key: "updated_by", label: "Updated by", type: "select", fk: profileFk, auto: true, autoOn: "both", hideInList: true },
    ],
  }),
];
